# Generated by Django 4.2.1 on 2023-05-29 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alerts', '0002_alter_alert_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, to_field='username', verbose_name='User'),
        ),
    ]
